version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: sport
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "8501:8501"
    depends_on:
      - db

  airflow:
    build:
      context: ./airflow
    container_name: airflow
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@db:5432/sport
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    entrypoint: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow webserver
      "

  airflow-init:
    build:
      context: ./airflow
    container_name: airflow-init
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@db:5432/sport
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "

  airflow-scheduler:
    build:
      context: ./airflow
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@db:5432/sport
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt

